### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by KitsuneRal**
Not having enough time for serious hacking, I took an opportunity to fix minor things here and there. Among highlights - `make install`, or rather, `cmake --build . --target install`, on Windows carry over the nevessary Qt libraries to the installation folder as well, so the whole build-install-run process becomes (almost) perfectly automated.

### CODE REVIEW

**Comment by KitsuneRal** [comment]
Thought AppVeyor claims that everything's fine, it's actually not - the libraries didn't get copied.

**Comment by KitsuneRal** [comment]
Feedback on installability under Linux is welcome.

**Comment by maralorn** [comment]
Builds fine at my system.

**Comment by KitsuneRal** [comment]
More fixes arrived upon code inspection in CLion. These should be pretty much harmless to anything.

**Pull request merged**
