### PR TITLE
Implemented user and room names according to the spec + minor tweaks and cleanup

### PR DESCRIPTION
**Pull request by KitsuneRal**
Basically, the main part is the last commit, I tried to give it a good description. If you need more clarifications, don't hesitate to ask. The background for these changes is in [sections 11.2.2.3-11.2.2.5 of the CS spec](https://matrix.org/docs/spec/r0.0.1/client_server.html#id184). Other commits are either supplementary to the last one, or are straightforward cleanup/tweaks.

### CODE REVIEW

**Comment by Fxrh** [comment]
Hi kitsune,

I merged all commits except the last one now.

**Comment by KitsuneRal** [comment]
Oh; I appreciate. I was going to split the commit but I've got a personal contingency and fell out of all activities for a week. I'm still planning to split in the nearest couple of days.

**Comment by Fxrh** [comment]
Oh, I hope it is not too bad... Take your time, I was just merging parts of the request because I needed the user() function ;)

**Comment by KitsuneRal** [comment]
The last commit will be rebased and split in a separate branch and PR.

**Pull request closed without merging**
