### PR TITLE
Chat widget love

### PR DESCRIPTION
**Pull request by KitsuneRal**
As described in the commit messages. Featured: support emotes (aka /me) :)

### CODE REVIEW

**Comment by Fxrh** [comment]
Nice :) But when trying to merge it, I get a build error:

/home/felix/Development/qmatrixclient/client/models/messageeventmodel.cpp:170:50: error: no viable conversion from 'QString' to 'QMatrixClient::User *'
            return m_currentRoom->roomMembername(e->userId());
                                                 ^~~~~~~~~~~
/home/felix/Development/qmatrixclient/lib/room.h:60:54: note: passing argument to parameter 'u' here
            Q_INVOKABLE QString roomMembername(User* u) const;
                                                     ^
/home/felix/Development/qmatrixclient/client/models/messageeventmodel.cpp:187:62: error: no viable conversion from 'QString' to 'QMatrixClient::User *'
                return QString(m_currentRoom->roomMembername(e->userId()) % " " % e->body());
                                                             ^~~~~~~~~~~
/home/felix/Development/qmatrixclient/lib/room.h:60:54: note: passing argument to parameter 'u' here
            Q_INVOKABLE QString roomMembername(User* u) const;

I can take a look at it, but not tonight anymore...

**Comment by KitsuneRal** [comment]
Oops, seems that his was based on an older commit and got rotten. I'll fix it.

**Comment by KitsuneRal** [comment]
Actually, the code base seems to be correct - the respective call in the lib has been introduced exactly in the commit this branch refers to (and master refers to an even newer commit). Did you update the lib submodule?
The other trouble is that this branch conflicts with null-pointer-fixes that just got merged - but that's easily fixable.

**Comment by Fxrh** [comment]
Ah, yes, sorry. Thanks!

**Pull request merged**
