### PR TITLE
Portability and CI

### PR DESCRIPTION
**Pull request by KitsuneRal**
This officially makes Quaternion buildable:
 - with Qt 5.2.1;
 - with Visual Studio (at least) 2013/2015 - probably, older ones too.

README.md is updated respectively.

### CODE REVIEW

**Comment by Fxrh** [comment]
Except for that question, everything looks good, and it's awesome to have CI for windows :)

**Comment by KitsuneRal** [comment]
I was just following the Travis documentation: one example is [here](https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step); and [this section](https://docs.travis-ci.com/user/languages/cpp/#Default-Test-Script) notes the default script command is actually building an autoconf-based project. And apparently, Travis doesn't have a dedicated test section.
...looking at which I now realize that CMake configuration should be in `script` too. Give me a moment.

**Comment by KitsuneRal** [comment]
AppVeyor's failure is bogus, it's due to an unconfigured project.

**Comment by Fxrh** [comment]
Looks good :)

**Comment by KitsuneRal** [comment]
Once merged, it builds :) https://ci.appveyor.com/project/KitsuneRal/quaternion-s8icw, for the record (it builds from Fxrh/Quaternion and will nag on all branches). The warnings are caused by a screwed warnings configuration, not by a bad Qt code :)

**Comment by Fxrh** [comment]
Hmm, do you know what is wrongly configured? Somehow, it seems it doesn't find the config file

**Comment by KitsuneRal** [comment]
If you mean the warnings configuration - it somehow fails to suppress many irrelevant warnings once switched from libqmatrixclient to Quaternion.
If you're trying to set up the AppVeyor configuration - probably you mistook the .yml file name (it's .appveyor.yml, in Linux fashion rather than Windows).

**Comment by Fxrh** [comment]
yes, thanks!

**Pull request merged**
